### ISSUE TITLE
关于KV高亮遇到的问题

### ISSUE THREAD

**Issue by ChouUn** [XavierCHN/Dota-Reborn-Package#1]
### 操作系统

Windows 7 旗舰版 SP1
### Sublime

Sublime Text 2.0.2 x64 
Sublime Text Build 3083 x64
## 问题

在纯净的sublime里（只有这个Package），打开`dota 2 beta\game\dota_addons\rpg_example\scripts\npc\npc_abilities_custom.txt`，无高亮下正常，用KV高亮卡死，五分钟内仍然未响应。
代码好像能打开，但是我台式跟笔记本，2和3版本都是血崩

**Comment by XavierCHN** [comment]
原因不明。。。 我用起来一切正常。。。 之后再看看。。。

**Comment by XavierCHN** [comment]
要不你试试把txt默认语法改成plain text之后打开，打开了之后再看看切换语法会不会有问题？
这个dota kv的语法不是我写的，所以debug起来会有一定难度。。。

**Comment by ChouUn** [comment]
切换也是卡死。部分地图的abilities_custom.txt会遇到这问题，<del>简单的能打开</del>。
我再试试别的电脑。叉大跟代码竟然都没遇到，2333。

ps：我debug出问题了，是space的缘故，如果是tab那么没问题。
**在复杂的文件里，**如果所有tab替换成连续的4个space我会卡死。
如果存在少于4个space则是没关系的。替换成3个space稍微卡一下也就好了。
估计是连续4个space会触发什么，所以我替换成了tab，解决了这个问题。

顺便对regex进行了修改，Noya鸽高兴的收下了。
原来noya鸽打开rpg_example的npc_abilities_custom.txt也崩了。
我会尝试着去fix一下

**Comment by ChouUn** [comment]
今天早上debug了一遍，value后面隔一个空格，直接加`//`注释，会导致卡死，然而tab并不会遇到这个。
我改出第二版后pull了，坐等noya鸽merge。
